// exhibition.model.ts
import { z } from "zod";

export const EXHIBITION_STATUSES = [
  "draft",
  "published",
  "ongoing",
  "ended",
  "archived",
] as const;

export type ExhibitionStatus = (typeof EXHIBITION_STATUSES)[number];

// Zod Schemas for API validation
export const ExhibitionSchema = z.object({
  exhibition_id: z.number(),
  exhibition_code: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  description_delta: z.any().nullable(), // JSON field from database (Quill Delta format)
  start_date: z.string(),
  end_date: z.string(),
  location: z.string().nullable(),
  organizer_name: z.string(),
  picture_path: z.string().nullable(),
  status: z.enum(EXHIBITION_STATUSES),
  created_by: z.number(),
  updated_by: z.number().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  archived_at: z.string().nullable(),
});

// Schema for Create Exhibition (excludes system-generated fields)
export const CreateExhibitionSchema = ExhibitionSchema.omit({
  exhibition_id: true,
  exhibition_code: true,   // Auto-generated by trigger
  created_by: true,        // Extracted from JWT token
  updated_by: true,        // System generated
  picture_path: true,      // Handled separately in file upload
  created_at: true,        // System generated
  updated_at: true,        // System generated
  archived_at: true,       // System generated
});

// Schema for Update Exhibition (all fields optional)
export const UpdateExhibitionSchema = CreateExhibitionSchema.partial();

// Inferred types from Zod schemas
export type Exhibition = z.infer<typeof ExhibitionSchema>;
export type CreateExhibitionInput = z.infer<typeof CreateExhibitionSchema>;
export type UpdateExhibitionInput = z.infer<typeof UpdateExhibitionSchema>;

// Database operation types
export interface AddExhibitionPayload {
  title: string;
  description?: string;
  description_delta?: string;
  start_date: string; // ISO datetime string
  end_date: string; // ISO datetime string
  location?: string;
  organizer_name: string;
  picture_path?: string;
  status?: ExhibitionStatus;
  created_by: number;
}

export type UpdateExhibitionPayload = Partial<{
  title: string;
  description: string | null;
  description_delta: string | null;
  start_date: string;
  end_date: string;
  location: string | null;
  organizer_name: string;
  picture_path: string | null;
  status: ExhibitionStatus;
}>;