// exhibition.model.ts
import { z } from "zod";

export const EXHIBITION_STATUSES = [
  "draft",
  "published",
  "ongoing",
  "ended",
  "archived",
] as const;

export type ExhibitionStatus = (typeof EXHIBITION_STATUSES)[number];

// Zod Schemas for API validation
export const ExhibitionSchema = z.object({
  exhibition_id: z.number(),
  exhibition_code: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  description_delta: z.any().nullable(), // JSON field from database (Quill Delta format)
  start_date: z.string(),
  end_date: z.string(),
  location: z.string().nullable(),
  organizer_name: z.string(),
  picture_path: z.string().nullable(),
  status: z.enum(EXHIBITION_STATUSES),
  created_by: z.number(),
  updated_by: z.number().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  archived_at: z.string().nullable(),
});

// Schema for Create Exhibition (excludes system-generated fields)
export const CreateExhibitionSchema = ExhibitionSchema.omit({
  exhibition_id: true,
  exhibition_code: true,   // Auto-generated by trigger
  created_by: true,        // Extracted from JWT token
  updated_by: true,        // System generated
  picture_path: true,      // Handled separately in file upload
  created_at: true,        // System generated
  updated_at: true,        // System generated
  archived_at: true,       // System generated
});

// Schema for Update Exhibition (all fields optional)
export const UpdateExhibitionSchema = CreateExhibitionSchema.partial();

// Schema for Add Exhibition (includes created_by and picture_path)
export const AddExhibitionPayloadSchema = CreateExhibitionSchema.extend({
  created_by: z.number(),
  picture_path: z.string().optional(),
});

// Schema for Update Exhibition Payload (includes picture_path)
export const UpdateExhibitionPayloadSchema = CreateExhibitionSchema.extend({
  picture_path: z.string().nullable().optional(),
}).partial();

// Inferred types from Zod schemas
export type Exhibition = z.infer<typeof ExhibitionSchema>;
export type CreateExhibitionInput = z.infer<typeof CreateExhibitionSchema>;
export type UpdateExhibitionInput = z.infer<typeof UpdateExhibitionSchema>;
export type AddExhibitionPayload = z.infer<typeof AddExhibitionPayloadSchema>;
export type UpdateExhibitionPayload = z.infer<typeof UpdateExhibitionPayloadSchema>;