// unit.model.ts
import { z } from "zod";

export const UNIT_TYPES = ["booth", "activity"] as const;

export type UnitType = (typeof UNIT_TYPES)[number];

// Zod Schemas for API validation
export const UnitSchema = z.object({
  unit_id: z.number(),
  unit_code: z.string().nullable(), // Auto-generated by trigger, always returned by DB
  exhibition_id: z.number(),
  unit_name: z.string(),
  unit_type: z.enum(UNIT_TYPES),
  description: z.string().nullable(),
  description_delta: z.any().nullable(), // JSON field from database
  staff_user_ids: z.array(z.number()), // Always present, can be empty array
  staff_names: z.array(z.string()), // Always present, can be empty array
  poster_url: z.string().nullable(),
  detail_pdf_url: z.string().nullable(),
  starts_at: z.string().nullable(),
  ends_at: z.string().nullable(),
});

// Schema for Create Unit (excludes unit_id, exhibition_id, staff info)
export const CreateUnitSchema = z.object({
  unit_name: z.string(),
  unit_type: z.enum(UNIT_TYPES),
  description: z.string().nullable().optional(),
  description_delta: z.string().nullable().optional(),
  staff_user_ids: z.array(z.number()).optional(),
  poster_url: z.string().nullable().optional(),
  detail_pdf_url: z.string().nullable().optional(),
  starts_at: z.string().nullable().optional(),
  ends_at: z.string().nullable().optional(),
});

// Schema for Update Unit (all fields optional)
export const UpdateUnitSchema = CreateUnitSchema.partial();

// Schema for Add Unit (includes exhibition_id)
export const AddUnitPayloadSchema = CreateUnitSchema.extend({
  exhibition_id: z.number(),
});

// Schema for Update Unit Payload
export const UpdateUnitPayloadSchema = CreateUnitSchema.partial();

// Schema for Unit Row Base (database row without staff info)
export const UnitRowBaseSchema = UnitSchema.omit({
  staff_user_ids: true,
  staff_names: true,
});

// Schema for Unit Row with Staff (database row with staff info)
export const UnitRowWithStaffSchema = UnitSchema;

// Schema for Unit Staff Row (from unit_staffs join)
export const UnitStaffRowSchema = z.object({
  unit_id: z.number(),
  staff_user_id: z.number(),
  full_name: z.string().nullable(),
});

// Inferred types from Zod schemas
export type Unit = z.infer<typeof UnitSchema>;
export type CreateUnitInput = z.infer<typeof CreateUnitSchema>;
export type UpdateUnitInput = z.infer<typeof UpdateUnitSchema>;
export type AddUnitPayload = z.infer<typeof AddUnitPayloadSchema>;
export type UpdateUnitPayload = z.infer<typeof UpdateUnitPayloadSchema>;
export type UnitRowBase = z.infer<typeof UnitRowBaseSchema>;
export type UnitRowWithStaff = z.infer<typeof UnitRowWithStaffSchema>;
export type UnitStaffRow = z.infer<typeof UnitStaffRowSchema>;
