// unit.model.ts
import { z } from "zod";

export const UNIT_TYPES = ["booth", "activity"] as const;

export type UnitType = (typeof UNIT_TYPES)[number];

// Zod Schemas for API validation
export const UnitSchema = z.object({
  unit_id: z.number(),
  unit_code: z.string().nullable(), // Auto-generated by trigger, always returned by DB
  exhibition_id: z.number(),
  unit_name: z.string(),
  unit_type: z.enum(UNIT_TYPES),
  description: z.string().nullable(),
  description_delta: z.any().nullable(), // JSON field from database
  staff_user_id: z.number().nullable(),
  staff_name: z.string().nullable(),
  staff_user_ids: z.array(z.number()), // Always present, can be empty array
  staff_names: z.array(z.string()), // Always present, can be empty array
  poster_url: z.string().nullable(),
  detail_pdf_url: z.string().nullable(),
  starts_at: z.string().nullable(),
  ends_at: z.string().nullable(),
});

// Schema for Create Unit (excludes unit_id, exhibition_id, staff info)
export const CreateUnitSchema = z.object({
  unit_name: z.string(),
  unit_type: z.enum(UNIT_TYPES),
  description: z.string().nullable().optional(),
  description_delta: z.string().nullable().optional(),
  staff_user_id: z.number().nullable().optional(),
  staff_user_ids: z.array(z.number()).optional(),
  poster_url: z.string().nullable().optional(),
  detail_pdf_url: z.string().nullable().optional(),
  starts_at: z.string().nullable().optional(),
  ends_at: z.string().nullable().optional(),
});

// Schema for Update Unit (all fields optional)
export const UpdateUnitSchema = CreateUnitSchema.partial();

// Inferred types from Zod schemas
export type Unit = z.infer<typeof UnitSchema>;
export type CreateUnitInput = z.infer<typeof CreateUnitSchema>;
export type UpdateUnitInput = z.infer<typeof UpdateUnitSchema>;

// Database operation types
export interface AddUnitPayload {
  exhibition_id: number;          // FK → exhibitions.exhibition_id
  unit_name: string;
  unit_type: UnitType;
  description?: string | null;
  description_delta?: string | null;
  staff_user_id?: number | null;  // FK → normal_users.user_id
  staff_user_ids?: number[];
  poster_url?: string | null;
  detail_pdf_url?: string | null;
  starts_at?: string | null;      // ISO datetime string
  ends_at?: string | null;        // ISO datetime string
}

export type UpdateUnitPayload = Partial<{
  unit_name: string;
  unit_type: UnitType;
  description: string | null;
  description_delta: string | null;
  staff_user_id: number | null;
  staff_user_ids: number[];
  poster_url: string | null;
  detail_pdf_url: string | null;
  starts_at: string | null;
  ends_at: string | null;
}>;

export type UnitRowBase = {
  unit_id: number;
  unit_code: string | null;
  exhibition_id: number;
  unit_name: string;
  unit_type: UnitType;
  description: string | null;
  description_delta: any | null; // JSON field
  poster_url: string | null;
  detail_pdf_url: string | null;
  starts_at: string | null;
  ends_at: string | null;
};

export type UnitRowWithStaff = UnitRowBase & {
  staff_user_id: number | null;
  staff_name: string | null;
  staff_user_ids: number[];
  staff_names: string[];
};

export type UnitStaffRow = {
  unit_id: number;
  staff_user_id: number;
  full_name: string | null;
};
