import type { FastifyInstance } from "fastify";

const schemas = [
  {
    $id: "Exhibition",
    type: "object",
    properties: {
      exhibition_id: { type: "integer", example: 42 },
      exhibition_code: { type: "string", example: "EXH-042" },
      title: { type: "string", example: "Tech Innovation Expo" },
      description: { type: ["string", "null"], example: "Annual technology showcase." },
      start_date: { type: "string", format: "date-time", example: "2024-05-01T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-05T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall A, Bangkok Convention Centre" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042.jpg" },
      status: { type: ["string", "null"], example: "published" },
      created_by: { type: ["integer", "null"], example: 7 },
    },
    required: ["exhibition_id", "title", "start_date", "end_date", "organizer_name"],
    examples: [
      {
        exhibition_id: 42,
        exhibition_code: "EXH-042",
        title: "Tech Innovation Expo",
        description: "Annual technology showcase.",
        start_date: "2024-05-01T09:00:00Z",
        end_date: "2024-05-05T17:00:00Z",
        location: "Hall A, Bangkok Convention Centre",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042.jpg",
        status: "published",
        created_by: 7,
      },
    ],
  },
  {
    $id: "Unit",
    type: "object",
    properties: {
      unit_id: { type: "integer", example: 105 },
      exhibition_id: { type: "integer", example: 42 },
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "booth" },
      description: { type: ["string", "null"], example: "Interactive demos of AI gadgets." },
      staff_user_id: { type: ["integer", "null"], example: 13 },
      staff_name: { type: ["string", "null"], example: "คุณสมชาย" },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T18:00:00Z" },
    },
    required: ["unit_id", "exhibition_id", "unit_name", "unit_type"],
    examples: [
      {
        unit_id: 105,
        exhibition_id: 42,
        unit_name: "AI Playground",
        unit_type: "booth",
        description: "Interactive demos of AI gadgets.",
        staff_user_id: 13,
        staff_name: "คุณสมชาย",
        poster_url: "uploads/units/ai-playground.png",
        starts_at: "2024-05-01T10:00:00Z",
        ends_at: "2024-05-01T18:00:00Z",
      },
    ],
  },
  {
    $id: "UserDropdownOption",
    type: "object",
    properties: {
      value: { type: "integer", example: 1 },
      label: { type: "string", example: "Alice Example" },
    },
    required: ["value", "label"],
    examples: [
      {
        value: 1,
        label: "Alice Example",
      },
    ],
  },
  {
    $id: "CreateExhibitionInput",
    type: "object",
    required: ["title", "start_date", "end_date", "organizer_name", "created_by"],
    properties: {
      title: { type: "string", example: "Tech Innovation Expo" },
      description: { type: ["string", "null"], example: "Annual technology showcase." },
      start_date: { type: "string", format: "date-time", example: "2024-05-01T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-05T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall A, Bangkok Convention Centre" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042.jpg" },
      status: {
        type: "string",
        enum: ["draft", "published", "ongoing", "ended", "archived"],
        example: "published",
      },
      created_by: { type: "integer", example: 7 },
    },
    examples: [
      {
        title: "Tech Innovation Expo",
        description: "Annual technology showcase.",
        start_date: "2024-05-01T09:00:00Z",
        end_date: "2024-05-05T17:00:00Z",
        location: "Hall A, Bangkok Convention Centre",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042.jpg",
        status: "published",
        created_by: 7,
      },
    ],
  },
  {
    $id: "UpdateExhibitionInput",
    type: "object",
    properties: {
      title: { type: "string", example: "Tech Innovation Expo - Day 2" },
      description: { type: ["string", "null"], example: "Updated description" },
      start_date: { type: "string", format: "date-time", example: "2024-05-02T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-06T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall B" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042-updated.jpg" },
      status: {
        type: "string",
        enum: ["draft", "published", "ongoing", "ended", "archived"],
      },
    },
    additionalProperties: false,
    examples: [
      {
        title: "Tech Innovation Expo - Day 2",
        description: "Updated description",
        start_date: "2024-05-02T09:00:00Z",
        end_date: "2024-05-06T17:00:00Z",
        location: "Hall B",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042-updated.jpg",
        status: "ongoing",
      },
    ],
  },
  {
    $id: "CreateUnitInput",
    type: "object",
    required: ["unit_name", "unit_type"],
    properties: {
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "booth" },
      description: { type: ["string", "null"], example: "Hands-on AI demo area." },
      staff_user_id: { type: ["integer", "null"], example: 13 },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T18:00:00Z" },
    },
    additionalProperties: false,
    examples: [
      {
        unit_name: "AI Playground",
        unit_type: "booth",
        description: "Hands-on AI demo area.",
        staff_user_id: 13,
        poster_url: "uploads/units/ai-playground.png",
        starts_at: "2024-05-01T10:00:00Z",
        ends_at: "2024-05-01T18:00:00Z",
      },
    ],
  },
  {
    $id: "UpdateUnitInput",
    type: "object",
    properties: {
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "activity" },
      description: { type: ["string", "null"], example: "Hands-on AI demo area." },
      staff_user_id: { type: ["integer", "null"], example: 13 },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-02T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-02T18:00:00Z" },
    },
    additionalProperties: false,
    examples: [
      {
        unit_name: "AI Playground - Day 2",
        unit_type: "activity",
        description: "Updated stage schedule.",
        staff_user_id: 99,
        poster_url: "uploads/units/ai-playground-day2.png",
        starts_at: "2024-05-02T10:00:00Z",
        ends_at: "2024-05-02T18:00:00Z",
      },
    ],
  },
];

export const registerSchemas = (app: FastifyInstance) => {
  schemas.forEach((schema) => app.addSchema(schema));
};
