import type { FastifyInstance } from "fastify";

const quillDeltaSchema = {
  type: "object",
  additionalProperties: true,
};

const schemas = [
  {
    $id: "Exhibition",
    type: "object",
    properties: {
      exhibition_id: { type: "integer", example: 42 },
      exhibition_code: { type: "string", example: "EXH-042" },
      title: { type: "string", example: "Tech Innovation Expo" },
      description: { type: ["string", "null"], example: "Annual technology showcase." },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Annual technology showcase.\n" }] },
      },
      start_date: { type: "string", format: "date-time", example: "2024-05-01T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-05T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall A, Bangkok Convention Centre" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042.jpg" },
      status: { type: ["string", "null"], example: "published" },
      created_by: { type: ["integer", "null"], example: 7 },
    },
    required: ["exhibition_id", "title", "start_date", "end_date", "organizer_name"],
    examples: [
      {
        exhibition_id: 42,
        exhibition_code: "EXH-042",
        title: "Tech Innovation Expo",
        description: "Annual technology showcase.",
        description_delta: { ops: [{ insert: "Annual technology showcase.\n" }] },
        start_date: "2024-05-01T09:00:00Z",
        end_date: "2024-05-05T17:00:00Z",
        location: "Hall A, Bangkok Convention Centre",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042.jpg",
        status: "published",
        created_by: 7,
      },
    ],
  },
  {
    $id: "Unit",
    type: "object",
    properties: {
      unit_id: { type: "integer", example: 105 },
      exhibition_id: { type: "integer", example: 42 },
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "booth" },
      description: { type: ["string", "null"], example: "Interactive demos of AI gadgets." },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Interactive demos of AI gadgets.\n" }] },
      },
      staff_user_ids: {
        type: "array",
        items: { type: "integer" },
        example: [13, 27],
      },
      staff_names: {
        type: "array",
        items: { type: "string" },
        example: ["คุณสมชาย", "คุณศิริพร"],
      },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      detail_pdf_url: { type: ["string", "null"], example: "uploads/units/EXP_PDF1234567890.pdf" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T18:00:00Z" },
    },
    required: ["unit_id", "exhibition_id", "unit_name", "unit_type"],
    examples: [
      {
        unit_id: 105,
        exhibition_id: 42,
        unit_name: "AI Playground",
        unit_type: "booth",
        description: "Interactive demos of AI gadgets.",
        description_delta: { ops: [{ insert: "Interactive demos of AI gadgets.\n" }] },
        staff_user_ids: [13, 27],
        staff_names: ["คุณสมชาย", "คุณศิริพร"],
        poster_url: "uploads/units/ai-playground.png",
        detail_pdf_url: "uploads/units/EXP_PDF1234567890.pdf",
        starts_at: "2024-05-01T10:00:00Z",
        ends_at: "2024-05-01T18:00:00Z",
      },
    ],
  },
  {
    $id: "UserDropdownOption",
    type: "object",
    properties: {
      value: { type: "integer", example: 1 },
      label: { type: "string", example: "Alice Example" },
    },
    required: ["value", "label"],
    examples: [
      {
        value: 1,
        label: "Alice Example",
      },
    ],
  },
  {
    $id: "CreateExhibitionInput",
    type: "object",
    required: ["title", "start_date", "end_date", "organizer_name", "created_by"],
    properties: {
      title: { type: "string", example: "Tech Innovation Expo" },
      description: { type: ["string", "null"], example: "Annual technology showcase." },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Annual technology showcase.\n" }] },
      },
      start_date: { type: "string", format: "date-time", example: "2024-05-01T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-05T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall A, Bangkok Convention Centre" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042.jpg" },
      status: {
        type: "string",
        enum: ["draft", "published", "ongoing", "ended", "archived"],
        example: "published",
      },
      created_by: { type: "integer", example: 7 },
    },
    examples: [
      {
        title: "Tech Innovation Expo",
        description: "Annual technology showcase.",
        description_delta: { ops: [{ insert: "Annual technology showcase.\n" }] },
        start_date: "2024-05-01T09:00:00Z",
        end_date: "2024-05-05T17:00:00Z",
        location: "Hall A, Bangkok Convention Centre",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042.jpg",
        status: "published",
        created_by: 7,
      },
    ],
  },
  {
    $id: "UpdateExhibitionInput",
    type: "object",
    properties: {
      title: { type: "string", example: "Tech Innovation Expo - Day 2" },
      description: { type: ["string", "null"], example: "Updated description" },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Updated description\n" }] },
      },
      start_date: { type: "string", format: "date-time", example: "2024-05-02T09:00:00Z" },
      end_date: { type: "string", format: "date-time", example: "2024-05-06T17:00:00Z" },
      location: { type: ["string", "null"], example: "Hall B" },
      organizer_name: { type: "string", example: "Innovate Co." },
      picture_path: { type: ["string", "null"], example: "uploads/exhibitions/exh-042-updated.jpg" },
      status: {
        type: "string",
        enum: ["draft", "published", "ongoing", "ended", "archived"],
      },
    },
    additionalProperties: false,
    examples: [
      {
        title: "Tech Innovation Expo - Day 2",
        description: "Updated description",
        description_delta: { ops: [{ insert: "Updated description\n" }] },
        start_date: "2024-05-02T09:00:00Z",
        end_date: "2024-05-06T17:00:00Z",
        location: "Hall B",
        organizer_name: "Innovate Co.",
        picture_path: "uploads/exhibitions/exh-042-updated.jpg",
        status: "ongoing",
      },
    ],
  },
  {
    $id: "CreateUnitInput",
    type: "object",
    required: ["unit_name", "unit_type"],
    properties: {
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "booth" },
      description: { type: ["string", "null"], example: "Hands-on AI demo area." },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Hands-on AI demo area.\n" }] },
      },
      staff_user_ids: {
        type: "array",
        items: { type: "integer" },
        description: "List of staff user IDs assigned to this unit",
        example: [13, 27],
      },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      detail_pdf_url: { type: ["string", "null"], example: "uploads/units/EXP_PDF1234567890.pdf" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-01T18:00:00Z" },
    },
    additionalProperties: false,
    examples: [
      {
        unit_name: "AI Playground",
        unit_type: "booth",
        description: "Hands-on AI demo area.",
        description_delta: { ops: [{ insert: "Hands-on AI demo area.\n" }] },
        staff_user_ids: [13],
        poster_url: "uploads/units/ai-playground.png",
        detail_pdf_url: "uploads/units/EXP_PDF1234567890.pdf",
        starts_at: "2024-05-01T10:00:00Z",
        ends_at: "2024-05-01T18:00:00Z",
      },
    ],
  },
  {
    $id: "UpdateUnitInput",
    type: "object",
    properties: {
      unit_name: { type: "string", example: "AI Playground" },
      unit_type: { type: "string", enum: ["booth", "activity"], example: "activity" },
      description: { type: ["string", "null"], example: "Hands-on AI demo area." },
      description_delta: {
        anyOf: [quillDeltaSchema, { type: "string" }, { type: "null" }],
        example: { ops: [{ insert: "Hands-on AI demo area.\n" }] },
      },
      staff_user_ids: {
        type: "array",
        items: { type: "integer" },
        example: [13, 27],
      },
      poster_url: { type: ["string", "null"], example: "uploads/units/ai-playground.png" },
      detail_pdf_url: { type: ["string", "null"], example: "uploads/units/EXP_PDF1234567890.pdf" },
      starts_at: { type: ["string", "null"], format: "date-time", example: "2024-05-02T10:00:00Z" },
      ends_at: { type: ["string", "null"], format: "date-time", example: "2024-05-02T18:00:00Z" },
    },
    additionalProperties: false,
    examples: [
      {
        unit_name: "AI Playground - Day 2",
        unit_type: "activity",
        description: "Updated stage schedule.",
        description_delta: { ops: [{ insert: "Updated stage schedule.\n" }] },
        staff_user_ids: [99],
        poster_url: "uploads/units/ai-playground-day2.png",
        detail_pdf_url: "uploads/units/EXP_PDF1234567890.pdf",
        starts_at: "2024-05-02T10:00:00Z",
        ends_at: "2024-05-02T18:00:00Z",
      },
    ],
  },
  {
    $id: "RegistrationInput",
    type: "object",
    required: ["exhibition_id", "full_name", "email", "role"],
    additionalProperties: false,
    properties: {
      exhibition_id: { type: "integer", minimum: 1, example: 1 },
      full_name: {
        type: "string",
        minLength: 1,
        example: "สมชาย ใจดี",
      },
      gender: {
        type: "string",
        enum: ["male", "female", "other"],
        example: "male",
      },
      birthdate: {
        type: "string",
        pattern: "^\\d{4}-\\d{2}-\\d{2}$",
        example: "1999-05-21",
      },
      email: {
        type: "string",
        format: "email",
        example: "user@example.com",
      },
      phone: {
        type: "string",
        minLength: 1,
        example: "0812345678",
      },
      role: {
        type: "string",
        enum: ["visitor", "staff"],
        example: "visitor",
      },
      unit_code: {
        type: "string",
        minLength: 1,
        example: "EX20250103",
        description: "Required when role is staff.",
      },
      line_user_id: {
        type: "string",
        minLength: 1,
        example: "Ue9761b5cc006f2b8c7d0897e8b272c61",
        description: "LINE user ID from LIFF integration.",
      },
    },
    examples: [
      {
        exhibition_id: 1,
        full_name: "สมชาย ใจดี",
        gender: "male",
        birthdate: "1999-05-21",
        email: "user@example.com",
        phone: "0812345678",
        role: "staff",
        unit_code: "EX20250103",
      },
    ],
  },
  {
    $id: "RegistrationResponse",
    type: "object",
    required: ["user", "registration"],
    properties: {
      user: {
        type: "object",
        required: ["user_id", "role"],
        properties: {
          user_id: { type: "integer", example: 123 },
          role: { type: "string", enum: ["user", "staff"], example: "staff" },
        },
      },
      registration: {
        type: "object",
        required: ["registration_id", "exhibition_id"],
        properties: {
          registration_id: { type: "integer", example: 456 },
          exhibition_id: { type: "integer", example: 1 },
        },
      },
      staff_linked: {
        type: "object",
        required: ["unit_id", "added"],
        properties: {
          unit_id: { type: "integer", example: 3 },
          added: { type: "boolean", example: true },
        },
      },
    },
    examples: [
      {
        user: { user_id: 123, role: "staff" },
        registration: { registration_id: 456, exhibition_id: 1 },
        staff_linked: { unit_id: 3, added: true },
      },
    ],
  },
  {
    $id: "Ticket",
    type: "object",
    properties: {
      ticket_id: { type: "integer", example: 1 },
      exhibition_id: { type: "integer", example: 1 },
      user_id: { type: "integer", example: 13 },
      ticket_code: { type: "string", example: "TKT-EX202501-00001" },
      ticket_type: { type: "string", enum: ["visitor", "staff", "vip"], example: "visitor" },
      issued_at: { type: "string", format: "date-time", example: "2025-10-20T14:30:00Z" },
      is_used: { type: "boolean", example: false },
      used_at: { type: ["string", "null"], format: "date-time", example: null },
    },
    required: ["ticket_id", "exhibition_id", "user_id", "ticket_code", "ticket_type", "issued_at", "is_used"],
    examples: [
      {
        ticket_id: 1,
        exhibition_id: 1,
        user_id: 13,
        ticket_code: "TKT-EX202501-00001",
        ticket_type: "visitor",
        issued_at: "2025-10-20T14:30:00Z",
        is_used: false,
        used_at: null,
      },
    ],
  },
  {
    $id: "TicketWithDetails",
    type: "object",
    properties: {
      ticket_id: { type: "integer", example: 1 },
      ticket_code: { type: "string", example: "TKT-EX202501-00001" },
      ticket_type: { type: "string", enum: ["visitor", "staff", "vip"], example: "visitor" },
      exhibition_id: { type: "integer", example: 1 },
      exhibition_code: { type: "string", example: "EX202501" },
      exhibition_title: { type: "string", example: "Smart Tech Expo 2025" },
      user_id: { type: "integer", example: 13 },
      user_name: { type: "string", example: "สมชาย ใจดี" },
      issued_at: { type: "string", format: "date-time", example: "2025-10-20T14:30:00Z" },
      is_used: { type: "boolean", example: false },
      used_at: { type: ["string", "null"], format: "date-time", example: null },
    },
    required: [
      "ticket_id",
      "ticket_code",
      "ticket_type",
      "exhibition_id",
      "exhibition_code",
      "exhibition_title",
      "user_id",
      "user_name",
      "issued_at",
      "is_used",
    ],
    examples: [
      {
        ticket_id: 1,
        ticket_code: "TKT-EX202501-00001",
        ticket_type: "visitor",
        exhibition_id: 1,
        exhibition_code: "EX202501",
        exhibition_title: "Smart Tech Expo 2025",
        user_id: 13,
        user_name: "สมชาย ใจดี",
        issued_at: "2025-10-20T14:30:00Z",
        is_used: false,
        used_at: null,
      },
    ],
  },
  {
    $id: "CreateTicketInput",
    type: "object",
    required: ["exhibition_id", "user_id", "ticket_type"],
    properties: {
      exhibition_id: { type: "integer", minimum: 1, example: 1 },
      user_id: { type: "integer", minimum: 1, example: 13 },
      ticket_type: { type: "string", enum: ["visitor", "staff", "vip"], example: "visitor" },
    },
    additionalProperties: false,
    examples: [
      {
        exhibition_id: 1,
        user_id: 13,
        ticket_type: "visitor",
      },
    ],
  },
  {
    $id: "QrTokenResponse",
    type: "object",
    required: ["qr_token", "expires_in"],
    properties: {
      qr_token: {
        type: "string",
        description: "JWT token containing user registration data for QR code display",
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEzLCJleHMiOlsxLDJdLCJpYXQiOjE3MDMxMDAwMDAsImV4cCI6MTcwMzEwMDMwMH0.signature",
      },
      expires_in: {
        type: "integer",
        description: "Token expiration time in seconds (300 = 5 minutes)",
        example: 300,
      },
    },
    examples: [
      {
        qr_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEzLCJleHMiOlsxLDJdLCJpYXQiOjE3MDMxMDAwMDAsImV4cCI6MTcwMzEwMDMwMH0.signature",
        expires_in: 300,
      },
    ],
  },
];

export const registerSchemas = (app: FastifyInstance) => {
  schemas.forEach((schema) => app.addSchema(schema));
};
